name = "Stellopolis"
author = "renamin"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74b6e587dd505709a41c45bd1e74496fe555e36a918a4931a4942fac61296de6"

[versions]
fabric = "0.16.13"
minecraft = "1.21.5"
